baseURL = 'https://cstheory.org'
title = 'SIGma'
theme = ['hugo-coder']
languageCode = "en-us"
defaultContentLanguage = "en"

[params]
    description = "The [WIP] Website for the SIG for Math and Algorithms" # website description
    info = "The SIG for Math and Algorithms"
    avatarURL = "images/avatar.jpg"
    since = 2022
    customSCSS = ["scss/style.scss"]
    colorScheme = "light"
    hideColorSchemeToggle = true
    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

[[menu.main]]
    identifier = "about" # section id
    name = "[About]"       # section display title
    url = "/about"       # path to the section
[[menu.main]]
    identifier = "meetings"
    name = "[Meetings]"
    url = "/meetings"

# https://forkaweso.me/Fork-Awesome/icons/
[[params.social]]
name = "Github"
icon = "fa fa-4x fa-github"
weight = 1
url = "https://github.com/SIGma-UIUC"

[[params.social]]
name = "Discord"
icon = "fa fa-4x fa-discord-alt"
weight = 1
url = "https://discord.gg/Sxf3h3pBbv"

[[params.social]]
name= "YouTube"
icon = "fa fa-4x fa-youtube-play"
weight = 1
url = "https://www.youtube.com/channel/UCStWQgYUnKdCk9TpwJ-_SRA"
