baseURL = 'http://example.org/'
title = 'SIGma'
theme = 'hugo-theme-texify'
languageCode = "en-us"

[params]
    description = "The [WIP] Website for the SIG for Math and Algorithms" # website description

[[menu.main]]
    identifier = "about" # section id
    name = "About"       # section display title
    url = "/about"           # path to the section
