baseURL = 'http://example.org/'
title = 'SIG for Math & Algos'
theme = 'hugo-theme-texify'
languageCode = "en-us"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

[[menu.main]]
identifier = "about" # section id
name = "About"       # section display title
url = "/about"           # path to the section
